version: '3'
services:
  docker02:
    image: 'incra/application'
    ports:
      - '8080:8080'
      - '50505:50505'
    environment:
      - APPLICATION=${application_name}
      - VERSION=${APP_VERSION}
      - ENVIRONMENT=${environment}

