FROM openjdk:8u131-jdk

ARG APP_VERSION
ARG APP
ARG JAR

ENV version ${APP_VERSION}
ENV application ${APP}

COPY build/libs/docker02-all-1.0.jar /home/docker02-all-1.0.jar

# port for microservice
EXPOSE 8080

# remote debugging port for IntelliJ
EXPOSE 50505

CMD ["java", \
     "-agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y", \
     "-jar", \
     "/home/docker02-all-1.0.jar"]
