version: '3'

services:
  docker02:
    image: 'company/application'
    ports:
      - '8080:8080'
      - '50505:50505'
    environment:
      - APPLICATION=${application_name}
      - VERSION=${APP_VERSION}
      - ENVIRONMENT=${environment}
    links:
      - mysql

  mysql:
    image: 'company/storage'
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "/storage/docker/mysql-datadir:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=docker02
      - MYSQL_USER=developer
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=123456
      - default_authentication_plugin=mysql_native_password
