FROM mysql

ARG APP_VERSION
ARG APP
ARG JAR

ENV version ${APP_VERSION}
ENV application ${APP}

CMD ["java", \
     "-agentlib:jdwp=transport=dt_socket,address=50505,suspend=n,server=y", \
     "-jar", \
     "/home/docker02-jar-with-dependencies.jar"]
